### ISSUE TITLE
The latest version of the Addon does not work in Italian

### ISSUE THREAD

**Issue by barramaurizio** [maxe-hsieh/subtitle_reader#13]
Hi, I would like to point out that the version of the Addon, subsequent to 2.83, does not work in Italian, so I am using the 2.83 which works perfectly. With the latest version, not only are the subtitles not read, but when for example you switch using "Control Y" from activating to deactivating the reading of subtitles, it is only stated when they are deactivated, but not when they are, or rather, they should be activated, since it doesn't work. Naturally I use Nvda 2023.3, all perfectly updated, functional and performing, so much so that the penultimate version actually works, but not the last one, which I have skipped for now, thanks. Tests with Microsoft Edge, Windows 11, but I think it matters little, the problem lies in the Addon update, thanks again.

**Comment by maxe-hsieh** [comment]
I think I've fixed it in version 2.91
