### ISSUE TITLE
我最近發現有一個插件可以讀出YouTube的中文字幕，您也可以參考

### ISSUE THREAD

**Issue by poposhi** [maxe-hsieh/subtitle_reader#15]
youtube-dubbing.com
这个插件是一个智能同步配音系统，主要功能包括：

智能同步配音：系统能够根据用户的操作实时适配，确保配音与视频同步，无论是暂停、拖动进度还是调整播放速度。
AI字幕生成：通过AI技术后台自动生成YouTube视频的字幕，提供更好的配音观看体验。好的字幕可以增强观看流畅度和理解度。

**Comment by maxe-hsieh** [comment]
我嘗試過了，沒有成功
