### ISSUE TITLE
The add-on is no longer able to report subtitles for Bilibili

### ISSUE THREAD

**Issue by cary-rowen** [maxe-hsieh/subtitle_reader#24]
Video for testing:
https://www.bilibili.com/video/BV15V411t7KL/?spm_id_from=333.337.search-card.all.click&vd_source=d94501c394f4ec46b2df7bc5760d4592

**Comment by maxe-hsieh** [comment]
Sorry, I can no longer find the subtitles on the screen using browse mode.

**Comment by cary-rowen** [comment]
Hi @maxe-hsieh 
I think you need to log in to bilibili.com first, then start playing the video, then in browse mode, press B to navigate to the "Play" button. And press the up arrow to see the subtitles.

**Comment by maxe-hsieh** [comment]
@cary-rowen I failed to register with my phone number.
Could you try to fix this issue and submit a pull request?

**Comment by cary-rowen** [comment]
Hi @maxe-hsieh 
@hwf1324 fixed the issue, I think you can merge the fix pr
