### ISSUE TITLE
Are the latest tested browser versions correct?

### ISSUE THREAD

**Issue by britechguy** [maxe-hsieh/subtitle_reader#25]
Given that the latest version of the add-on dates from 3 weeks ago, it seems almost impossible that the latest versions of the various browsers on which it's been tested are accurate.  

The list reads:
Google Chrome (97.0.4692.99 (正式版本) (64 位元))
Mozilla Firefox (77.0.1（64 位元）)
Microsoft Edge (97.0.1072.76 (官方組建) (64 位元))
Brave (1.34.81 Chromium: 97.0.4692.99 (正式版本) (64 位元))

and the latest versions of these respective browsers are many releases later:

Google Chrome (130.0.6723.69)
Mozilla Firefox (131.0.3 (64-bit))
Microsoft Edge (Version 130.0.2849.52)
Brave (v1.71.114)

**Comment by maxe-hsieh** [comment]
You're right, because later I discovered that listing these versions was meaningless, I just forgot to delete this entry.
After all, you can't not update your browser.
