### ISSUE TITLE
阅读中断

### ISSUE THREAD

**Issue by benshgit** [maxe-hsieh/subtitle_reader#3]
当字幕内容变化时，阅读就会中断。也就是说，每次只能阅读一句话。之后，需要滑鼠在字幕上移动一下，才会重新阅读。

**Comment by maxe-hsieh** [comment]
請問您在哪個網站使用字幕閱讀器呢，以及您使用哪個瀏覽器。另外建議您使用 tab 鍵，將焦點移至播放器的範圍，但不要停留於字幕之上，因為當字幕更換時，焦點可能會失焦並離開播放器的範圍，最好是停在播放器的暫停按鈕上。

**Comment by benshgit** [comment]
用Chrome 浏览youtube，无论怎样做，都无法让阅读器持续阅读字幕。

**Comment by maxe-hsieh** [comment]
那請提供您觀看的影片網址，讓我進行測試。

**Comment by benshgit** [comment]
随便选一个有中文字幕的Youtube影片试试就知道了。
