### ISSUE TITLE
With NVDA English or Italian, the translation does not appear

### ISSUE THREAD

**Issue by Ambro86** [maxe-hsieh/subtitle_reader#8]
Hello, first of all thank you so much for this project of yours which is really fabulous. I've been looking for an addon to let me read youtube subtitles for a long time. Could you correct one thing? I use Nvda in Italian, but I tried to change the language from general settings, putting it in English, and there is the same problem. The menu, from nvda, tools, appears in Chinese.
Thanks if you will fix this, because the insert y command reads in Chinese too.

**Comment by maxe-hsieh** [comment]
fixed on 2.81
